services:
  app:
    build: .
    container_name: autoML
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - app

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mongo_data:
    driver: local